/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AccommodationOption = {
  _type: "accommodationOption";
  level: "classic" | "comfort" | "luxury";
  image?: TripImage;
  description: string;
  packageNote?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type TripImage = {
  _type: "tripImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
};

export type SeasonalRate = {
  _type: "seasonalRate";
  season: "low" | "mid" | "high" | "peak" | "custom";
  months: Array<string>;
  customLabel?: string;
  priceForTwo: number;
  priceForFour: number;
  priceForSixPlus: number;
};

export type ItineraryDay = {
  _type: "itineraryDay";
  locations: Array<string>;
  description: string;
  activities: Array<string>;
  meals?: Array<string>;
  overnightType: "lodge" | "tented-camp" | "hotel" | "beach-resort" | "mountain-hut" | "no-overnight";
  accommodationName?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Trip = {
  _id: string;
  _type: "trip";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  tripType: "private-safari" | "wildlife-safari" | "mountain-trekking" | "beach" | "safari-plus-beach" | "family" | "honeymoon" | "luxury";
  badge?: "best-seller" | "new" | "family-favourite" | "luxury-pick";
  coverImage?: TripImage;
  summary: string;
  days: number;
  nights: number;
  startingPrice: number;
  itineraryPdf?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  atAGlance: Array<string>;
  overview: string;
  highlights: Array<string>;
  itinerary: Array<{
    _key: string;
  } & ItineraryDay>;
  seasonalRates: Array<{
    _key: string;
  } & SeasonalRate>;
  included: Array<string>;
  extraIncluded?: Array<string>;
  excluded?: Array<string>;
  extraExcluded?: Array<string>;
  accommodationOptions: Array<{
    _key: string;
  } & AccommodationOption>;
  gallery?: Array<{
    _key: string;
  } & TripImage>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = AccommodationOption | SanityImageAssetReference | TripImage | SeasonalRate | ItineraryDay | SanityFileAssetReference | Trip | SanityImageCrop | SanityImageHotspot | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../lib/queries.ts
// Variable: TRIP_BY_SLUG_QUERY
// Query: *[_type == "trip" && slug.current == $slug][0] {    _id,    _updatedAt,    title,    "slug": slug.current,    tripType,    badge,    coverImage {asset->{_id, url}, alt, hotspot, crop},    summary,    days,    nights,    startingPrice,    "itineraryPdfUrl": itineraryPdf.asset->url,    atAGlance,    overview,    highlights,    itinerary[] {      _key,      locations,      description,      activities,      "meals": coalesce(meals, []),      overnightType,      accommodationName    },    seasonalRates[] {      _key,      season,      months,      customLabel,      priceForTwo,      priceForFour,      priceForSixPlus    },    included,    "extraIncluded": coalesce(extraIncluded, []),    "excluded": coalesce(excluded, []),    "extraExcluded": coalesce(extraExcluded, []),    "accommodationOptions": coalesce(accommodationOptions[] {      _key,      level,      image {asset->{_id, url}, alt, hotspot, crop},      description,      packageNote    }, []),    "gallery": coalesce(gallery[] {      _key,      asset->{_id, url},      alt,      hotspot,      crop    }, [])  }
export type TRIP_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string;
  slug: string;
  tripType: "beach" | "family" | "honeymoon" | "luxury" | "mountain-trekking" | "private-safari" | "safari-plus-beach" | "wildlife-safari";
  badge: "best-seller" | "family-favourite" | "luxury-pick" | "new" | null;
  coverImage: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  summary: string;
  days: number;
  nights: number;
  startingPrice: number;
  itineraryPdfUrl: string | null;
  atAGlance: Array<string>;
  overview: string;
  highlights: Array<string>;
  itinerary: Array<{
    _key: string;
    locations: Array<string>;
    description: string;
    activities: Array<string>;
    meals: Array<string> | Array<never>;
    overnightType: "beach-resort" | "hotel" | "lodge" | "mountain-hut" | "no-overnight" | "tented-camp";
    accommodationName: string | null;
  }>;
  seasonalRates: Array<{
    _key: string;
    season: "custom" | "high" | "low" | "mid" | "peak";
    months: Array<string>;
    customLabel: string | null;
    priceForTwo: number;
    priceForFour: number;
    priceForSixPlus: number;
  }>;
  included: Array<string>;
  extraIncluded: Array<string> | Array<never>;
  excluded: Array<string> | Array<never>;
  extraExcluded: Array<string> | Array<never>;
  accommodationOptions: Array<{
    _key: string;
    level: "classic" | "comfort" | "luxury";
    image: {
      asset: {
        _id: string;
        url: string;
      } | null;
      alt: string;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
    } | null;
    description: string;
    packageNote: string | null;
  }>;
  gallery: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | Array<never>;
} | null;

// Source: ../lib/queries.ts
// Variable: RELATED_TRIPS_BY_TYPE_QUERY
// Query: *[    _type == "trip" &&    _id != $id &&    tripType == $tripType &&    defined(slug.current)  ] | order(_createdAt desc)[0...3] {    _id,    title,    "slug": slug.current,    tripType,    coverImage {asset->{_id, url}, alt, hotspot, crop},    days,    nights,    startingPrice  }
export type RELATED_TRIPS_BY_TYPE_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  tripType: "beach" | "family" | "honeymoon" | "luxury" | "mountain-trekking" | "private-safari" | "safari-plus-beach" | "wildlife-safari";
  coverImage: {
    asset: {
      _id: string;
      url: string;
    } | null;
    alt: string;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  days: number;
  nights: number;
  startingPrice: number;
}>;

// Source: ../lib/queries.ts
// Variable: TRIPS_FOR_LIST_QUERY
// Query: *[_type == "trip" && defined(slug.current)] | order(title asc) {    _id,    title,    "slug": slug.current,    tripType,    badge,    summary,    days,    nights,    startingPrice,    "imageUrl": coverImage.asset->url  }
export type TRIPS_FOR_LIST_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  tripType: "beach" | "family" | "honeymoon" | "luxury" | "mountain-trekking" | "private-safari" | "safari-plus-beach" | "wildlife-safari";
  badge: "best-seller" | "family-favourite" | "luxury-pick" | "new" | null;
  summary: string;
  days: number;
  nights: number;
  startingPrice: number;
  imageUrl: string | null;
}>;

// Source: ../lib/queries.ts
// Variable: TRIP_SLUGS_QUERY
// Query: *[_type == "trip" && defined(slug.current)][]{"slug": slug.current}
export type TRIP_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;
